### ISSUE TITLE
Dockerfile upgrade, need help with this one!

### ISSUE THREAD

**Issue by JasonLandbridge** [PlexRipper/PlexRipper#208]
Hi there,

**The problem**

The [Dockerfile](https://github.com/PlexRipper/PlexRipper/blob/dev/Dockerfile) currently used to build PlexRipper "works", but there is an issue where permissions for files that are created through PlexRipper have the `root` owner. Which means that all files that are downloaded need to be changed manually by the user before they can be used, which is really annoying. 

**Possible solution**

Ideally I would like to implement the same system [LinuxServer.io](https://docs.linuxserver.io/) does with their Docker images which requires the user to supply a UserId (PUID) and GroupId (GUID) when running PlexRipper. 
More can be read here about this system: https://docs.linuxserver.io/general/understanding-puid-and-pgid

I have read much about it but I'm honestly struggling with making this work. I "think" that I need to inherit from their [Alpine base image](https://github.com/linuxserver/docker-baseimage-alpine) and then create the correct .NET environment which I can then use to setup PlexRipper in there? What I have understood as well is that it makes heavy use of [S6-Overlay](https://github.com/just-containers/s6-overlay) which looks awesome! It would allow PlexRipper to run a different database then SQLite, while still always being a single container image and easy to setup. And maybe I could then have PlexRipper run on ARM64 as well, but that needs some more investigating

Anyway, can anyone rewrite the Dockerfile for PlexRipper to make use of the above?

Examples that work with .NET projects:
 - [LinuxServer.io Radarr](https://github.com/linuxserver/docker-radarr/blob/master/Dockerfile) 
 - [LinuxServer.io Sonarr](https://github.com/linuxserver/docker-sonarr/blob/master/Dockerfile)

Further documentation:
 - https://www.linuxserver.io/blog/how-is-container-formed
 - https://www.linuxserver.io/blog/brand-new
 - https://github.com/linuxserver/docker-baseimage-alpine
 - https://github.com/just-containers/s6-overlay

Related issues:
 - https://github.com/PlexRipper/PlexRipper/issues/87
 - https://github.com/PlexRipper/PlexRipper/issues/137

**Comment by AstralDestiny** [comment]
On runtime you can make it write as a different user by specifying a user flag in the run or the compose, 

docker run --user PUID:PGID blah blah
I don't use run commands very often so I can't help with the exact full command but adding that should be your ticket
You don't need to change it on buildtime just change the user at runtime so files are written with said user. :)
```yml
version: '3.4'
services:
  plexripper:
    container_name: PlexRipper
    image: plexripper/plexripper
    build:
      context: .
      dockerfile: ./Dockerfile
    user: PUID:PGID # find via id <user> changing this will bind to an actual host user and preferably don't give it a user that has docker group access on the host or has sudo permissions on the host for security sanity. 
    ports:
      # Web UI & Web API
      - '7000:7000'
    restart: unless-stopped
    volumes:
      - /mnt/PROJECTS/PlexRipperCache/Config:/Config
      - /mnt/PROJECTS/PlexRipperCache/Downloads:/Downloads
      - /mnt/PROJECTS/PlexRipperCache/Movies:/Movies
      - /mnt/PROJECTS/PlexRipperCache/TvShows:/TvShows
      ```
