### ISSUE TITLE
Implement multi-architecture base images in Dockerfile to support ARMv7 (Currently only ARM64/AMD64(

### ISSUE THREAD

**Issue by JasonLandbridge** [PlexRipper/PlexRipper#363]
## EDIT: The Dockerfile should work but it needs to be build on a ARM64 / ARM7 Device! Which is currently not happening

Hi there!

A feature that has been asked for many times is finally upon us! The [plexripper:dev](https://hub.docker.com/r/plexripper/plexripper/tags) now has ARM64 and ARMv7 support, but I have no idea if it works since I don't have the hardware to test it.

Anyone care to test it out and let me know if it runs correctly?

The process followed: [Improving multi-platform container support](https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/)
The Dockerfile: https://github.com/PlexRipper/PlexRipper/blob/dev/docker/Dockerfile

![image](https://github.com/user-attachments/assets/6ec06bf4-5250-405c-ada4-cf93a1a56ad5)

**Comment by ThaMattie** [comment]
Hi,
I had plexripper:test running, I used the same compose file and changed it to plexripper:dev, but that one fails to run (logging):
exec /init: exec format error

**Comment by JasonLandbridge** [comment]
> Hi, I had plexripper:test running, I used the same compose file and changed it to plexripper:dev, but that one fails to run (logging): exec /init: exec format error

@ThaMattie Can you post the full logs or error?

**Comment by ThaMattie** [comment]
That is the full logging, it keeps repeating that, nothing else

https://stackoverflow.com/a/64215125

**Comment by JasonLandbridge** [comment]
@ThaMattie That is very weird, what is your hardware and can you post your docker compose? And did you make sure to update the plexripper:dev image that you got the latest?

**Comment by JasonLandbridge** [comment]
@ThaMattie Chat-GPT to the rescue:

Can you try to set the platform:

```yaml
version: '3.8'
services:
  my_service:
    image: your-image:tag
    platform: linux/arm64 #<== DO THIS
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=some_value
```

**Comment by ThaMattie** [comment]
I have a Raspberry Pi 4, 8gb (ARM64). The compose file I used:

```yaml
---
version: '3.4'
services:
  plexripper:
    container_name: plexripper-dev
    image: plexripper/plexripper:dev
    ports:
      # Web UI & Web API
      - 7000:7000
    restart: unless-stopped
    volumes:
      - ${config}/plexripper-dev:/Config
      - ${config}/plexripper-dev/downloads:/Downloads
      - ${config}/plexripper-dev/incomplete:/incomplete
    networks:
      - public

networks:
  public:
    external: true
```
image:
![image](https://github.com/user-attachments/assets/13a55c10-3520-46a2-8d70-7fc052ec1975)

logs:
![image](https://github.com/user-attachments/assets/81112525-e561-4962-b0f2-2151f92d7f91)

I will try with the platform next (although this is the first image I ever had to use that)
